### ISSUE TITLE
TypeError: 'type' object is not subscriptable

### ISSUE THREAD

**Issue by witwiki** [cowprotocol/solver-template-py#21]
A Type Error occur because of:

`TokenDict = dict[Token, TokenInfo]`

Consider assigning dummy variables when defining them? 

Solution: https://stackoverflow.com/questions/26920955/typeerror-type-object-is-not-subscriptable-when-indexing-in-to-a-dictionary

**Comment by bh2smith** [comment]
Think you could give an example of where this happened. Would be a lot easier to check, fix and test the solution.

**Comment by witwiki** [comment]
Yes, sorry about that. 

This was in `./src/models/token.py` line 126.

I actually didn't do anything in particular. I just ran the code as per the instructions in the README.md under this repo.

Once I activated by `venv` as per the instructions, I ran `python -m src._server` under the **Run Solver Server** heading.

Once I ran this, it gave me the below output

```
File "/home/witwiki/GitHub/solver-template-py/src/models/token.py", line 126, in <module>
    TokenDict = dict[Token, TokenInfo]
TypeError: 'type' object is not subscriptable
```

**Comment by bh2smith** [comment]
Right but can you reproduce this with example input? I would love to have the input that caused this.

**Comment by bh2smith** [comment]
Yes, I am like 99% sure you are using an old version of python that does not support Type Declarations. Please ensure that you are using a python version >= 3.7.

**Comment by bh2smith** [comment]
Also - see [this answer](https://stackoverflow.com/a/71062520/5601507) in the stack exchange thread linked in issue description.
